//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCaPhe.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopCaPhe.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string iback {
            get {
                return ResourceManager.GetString("iback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Manage.
        /// </summary>
        public static string ibillmanage {
            get {
                return ResourceManager.GetString("ibillmanage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Category.
        /// </summary>
        public static string icategorydetail {
            get {
                return ResourceManager.GetString("icategorydetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string icategoryname {
            get {
                return ResourceManager.GetString("icategoryname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Child Menu.
        /// </summary>
        public static string ichildmenu {
            get {
                return ResourceManager.GetString("ichildmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Img.
        /// </summary>
        public static string ichooseimg {
            get {
                return ResourceManager.GetString("ichooseimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string icreate {
            get {
                return ResourceManager.GetString("icreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Day.
        /// </summary>
        public static string icreateday {
            get {
                return ResourceManager.GetString("icreateday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Manage.
        /// </summary>
        public static string icreateloai {
            get {
                return ResourceManager.GetString("icreateloai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        public static string icreateproduct {
            get {
                return ResourceManager.GetString("icreateproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string idelete {
            get {
                return ResourceManager.GetString("idelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category.
        /// </summary>
        public static string ideletecategory {
            get {
                return ResourceManager.GetString("ideletecategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Menu.
        /// </summary>
        public static string ideletemenu {
            get {
                return ResourceManager.GetString("ideletemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string ideleteproduct {
            get {
                return ResourceManager.GetString("ideleteproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Product.
        /// </summary>
        public static string idetailproduct {
            get {
                return ResourceManager.GetString("idetailproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string iedit {
            get {
                return ResourceManager.GetString("iedit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Menu.
        /// </summary>
        public static string ieditmenu {
            get {
                return ResourceManager.GetString("ieditmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string iHome {
            get {
                return ResourceManager.GetString("iHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string iID {
            get {
                return ResourceManager.GetString("iID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Child Menu(if have).
        /// </summary>
        public static string iidmenu {
            get {
                return ResourceManager.GetString("iidmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string iimg {
            get {
                return ResourceManager.GetString("iimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Menu.
        /// </summary>
        public static string ilinkmenu {
            get {
                return ResourceManager.GetString("ilinkmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type.
        /// </summary>
        public static string iloaisp {
            get {
                return ResourceManager.GetString("iloaisp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Manage.
        /// </summary>
        public static string imenu {
            get {
                return ResourceManager.GetString("imenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu detail.
        /// </summary>
        public static string imenudetail {
            get {
                return ResourceManager.GetString("imenudetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu name.
        /// </summary>
        public static string imenuname {
            get {
                return ResourceManager.GetString("imenuname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string imota {
            get {
                return ResourceManager.GetString("imota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string iout {
            get {
                return ResourceManager.GetString("iout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string iprice {
            get {
                return ResourceManager.GetString("iprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Manage.
        /// </summary>
        public static string iproduct {
            get {
                return ResourceManager.GetString("iproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string iproductname {
            get {
                return ResourceManager.GetString("iproductname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue Manage.
        /// </summary>
        public static string irevenue {
            get {
                return ResourceManager.GetString("irevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string isave {
            get {
                return ResourceManager.GetString("isave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string istatus {
            get {
                return ResourceManager.GetString("istatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sumary.
        /// </summary>
        public static string isumary {
            get {
                return ResourceManager.GetString("isumary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Coffee Manage.
        /// </summary>
        public static string ititle {
            get {
                return ResourceManager.GetString("ititle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string iunit {
            get {
                return ResourceManager.GetString("iunit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        public static string iupdatedate {
            get {
                return ResourceManager.GetString("iupdatedate", resourceCulture);
            }
        }
    }
}
