//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCaPhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIASANPHAM
    {
        public int MaDG { get; set; }
        public int MaSP { get; set; }
        public string HoTenKH { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> DiemDG { get; set; }
        public string TenDN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
